import { expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

/**
 * Nothing a schema file reaches may name a runtime.
 *
 * `drizzle-kit generate` runs under **Node**, and every module's schema imports
 * `@sentrello/db` for the `organizations` table its rows hang from. So the whole
 * import graph behind this package is read by Node — and `Bun` is not defined
 * there. One import of `hono/bun`, four levels down in the SDK, stopped
 * `db:generate` working in every module in three repositories with
 * `ReferenceError: Bun is not defined`, thrown inside hono's own adapter before
 * a single table was read. Nothing failed loudly: migrations are generated by
 * hand, so it was found weeks later by somebody adding an index.
 *
 * The graph is walked rather than the directory listed, because what matters is
 * what is *reachable* — a runtime-specific file nothing imports costs nothing.
 */
const HERE = resolve(import.meta.dir, "../../..");

/** The entry points a schema file is allowed to use. */
const ROOTS = [
  "packages/db/src/index.ts",
  "packages/db/src/orm.ts",
  "packages/db/src/schema.ts",
];

/** Imports that only exist in Bun, which is the whole of the problem. */
const NEEDS_BUN = /^(?:bun(?::|$)|hono\/bun$)/;

function importsIn(source: string): string[] {
  const out: string[] = [];
  for (const [, named] of source.matchAll(
    /(?:^|\n)\s*(?:import|export)[\s\S]*?from\s*["']([^"']+)["']/g,
  )) {
    if (named) out.push(named);
  }
  for (const [, bare] of source.matchAll(
    /(?:^|\n)\s*import\s*["']([^"']+)["']/g,
  )) {
    if (bare) out.push(bare);
  }
  return out;
}

/** A specifier as a file in this repository, or nothing if it is outside it. */
function fileFor(specifier: string, from: string): string | null {
  if (specifier.startsWith(".")) {
    const base = resolve(dirname(from), specifier);
    for (const candidate of [
      base,
      `${base}.ts`,
      `${base}.tsx`,
      join(base, "index.ts"),
    ]) {
      if (existsSync(candidate) && candidate.endsWith(".ts")) return candidate;
    }
    return null;
  }
  const ours = /^@sentrello\/([^/]+)(?:\/(.+))?$/.exec(specifier);
  if (!ours) return null;
  const [, pkg, sub] = ours;
  const base = join(HERE, "packages", pkg ?? "", "src");
  for (const candidate of sub
    ? [join(base, `${sub}.ts`), join(base, sub, "index.ts")]
    : [join(base, "index.ts")]) {
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

test("nothing a module's schema reaches needs Bun to be defined", () => {
  const seen = new Set<string>();
  const queue = ROOTS.map((r) => join(HERE, r));
  const offenders: string[] = [];

  while (queue.length > 0) {
    const file = queue.pop();
    if (!file || seen.has(file)) continue;
    seen.add(file);

    const source = readFileSync(file, "utf8");
    for (const specifier of importsIn(source)) {
      if (NEEDS_BUN.test(specifier)) {
        offenders.push(`${relative(HERE, file)} imports ${specifier}`);
        continue;
      }
      const next = fileFor(specifier, file);
      if (next) queue.push(next);
    }
  }

  // So a walk that silently reached nothing cannot pass as "all clear". The
  // graph is the SDK, the schema, the ORM re-exports and the retention policies.
  expect(seen.size).toBeGreaterThan(20);
  expect(offenders).toEqual([]);
});
