import { expect, test } from "bun:test";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * What is allowed to sit in `docs/` at the top level of this repository.
 *
 * This repository is public. The design notes each module is built from — the
 * parity audits — are not: they describe what was studied, what was taken and
 * what was deliberately left, module by module. That is the most useful
 * document in the project and the one least suited to being world-readable,
 * so it lives outside every repository.
 *
 * Five of them were here until 2026-09-07. They came out on James's
 * instruction, and the rule holds for every platform or module build after
 * this one: the audit is written, and it is written somewhere private.
 *
 * A test rather than a written-down rule, because the rule has been true for a
 * while and the files were here anyway. The failure mode is not somebody
 * disagreeing with it, it is somebody writing `docs/booking.md` on a Friday
 * without thinking about it.
 *
 * `docs/site/` is deliberately not covered: it is the published product
 * documentation, written for customers, and belongs in the open.
 */
const ALLOWED = new Set(["self-hosting.md"]);

test("only self-hosting.md sits at the top of docs", () => {
  const dir = join(import.meta.dir, "../../../docs");
  const loose = readdirSync(dir).filter(
    (name) => name.endsWith(".md") && !statSync(join(dir, name)).isDirectory(),
  );

  // The list emptying would pass this without checking anything, and the file
  // it names is the one a self-hoster actually needs.
  expect(loose).toContain("self-hosting.md");

  const unexpected = loose.filter((name) => !ALLOWED.has(name));
  expect(
    unexpected,
    "design notes and parity audits belong in ~/Documents/Sentrello-Private/audits, not in a public repository",
  ).toEqual([]);
});

/**
 * The legal documents here are a copy, and a copy has to be able to prove it.
 *
 * sentrello.com serves these; this repository carries them so that an AGPL
 * project's licence talk is not only on a marketing site. Each one says the
 * website governs. By 1 October four site-side corrections had failed to reach
 * the copy — a clause describing a collection that never happened, an address,
 * four whole sections of the trademark page, and a licence check still called
 * daily eleven days after the cron changed.
 *
 * They are generated now (`scripts/sync-legal.mjs` in the site repository,
 * whose gate refuses a build when the two disagree). This is the half of that
 * which lives here: a hand-edit is caught in the repository where somebody
 * made it, rather than next time the site happens to be built.
 *
 * `security.md` is exempt and is the reason the rule exists: its page is an
 * Astro component rather than markdown, so its copy is converted by hand — and
 * it was the worst file in the set, with three false claims, six stray list
 * markers and a missing section that made the page misleading.
 */
const GENERATED_EXEMPT = new Set(["security.md"]);

test("every legal document says it is generated, and from where", () => {
  const dir = join(import.meta.dir, "../../../legal");
  const pages = readdirSync(dir).filter((name) => name.endsWith(".md"));

  // Not vacuous: there are documents, and most of them are generated.
  expect(pages.length).toBeGreaterThan(5);

  const handWritten = pages
    .filter((name) => !GENERATED_EXEMPT.has(name))
    .filter((name) => {
      const text = readFileSync(join(dir, name), "utf8");
      return (
        !text.includes("Generated from the marketing site's own source") ||
        !text.includes("Do not edit this file")
      );
    });

  expect(handWritten).toEqual([]);
});
