/**
 * The platform's own icons.
 *
 * The drawings are the streamline-flex set, credited in `NOTICE` at the
 * root of this repository.
 *
 * **They are drawn on a 14x14 grid, not 24x24.** This file said 24 for
 * weeks and nobody checked: every icon in the product was therefore drawn
 * at 58% of its size, anchored to the top-left of its own box. On a label
 * it reads as a slightly small picture; on the navigation rail, where the
 * icon is the only thing naming a section, four of them sat at four
 * different apparent sizes with the space above and left of each one
 * belonging to nothing.
 *
 * The marks in `HOUSE` below are on the same grid for the same reason —
 * one coordinate system, or the next drawing added lands in the wrong one.
 *
 * `icon-flex.ts` is generated by `scripts/fetch-icons.mjs`, and the map
 * of which drawing means what lives in that script — that is the file to
 * edit when a module needs an icon this set has never been asked for.
 *
 * Set by James on 21 September 2026, against a folder of samples: the icons
 * should look drawn rather than drafted.
 */
import { FLEX, FLEX_GRID } from "./icon-flex";

/**
 * The marks that are geometry rather than pictures, drawn here.
 *
 * An icon set is drawn for icons, and a chevron, a plus and an ellipsis taken
 * from one arrive as small illustrations of those things — in the set's hand,
 * at the set's weight, beside a label they are meant to be subordinate to.
 * They are not illustrations. A plus is two strokes crossing. An ellipsis is
 * three dots. A caret is two hairlines meeting at a corner, and that one is
 * drawn in CSS because it also has to rotate.
 *
 * This set has no plus and no ellipsis at all, so the alternative was the
 * nearest picture that contained one — an application window with a plus in
 * the corner for "add a record", a telephone keypad for an overflow menu.
 * Both were placeholders and both said so in the map they came from.
 *
 * Stroked, not filled, unlike everything in FLEX: the weight of a rule is the
 * point of them. 0.95 on the 14x14 grid renders as a hair over 1px at the
 * 18px the app draws, which is the weight of the rules beside them — and is
 * the same stroke the set's own drawings carry, so a mark and a picture sit
 * at one weight beside each other.
 *
 * Ours, so they carry no attribution and the NOTICE stays true to what it
 * describes.
 */
const HOUSE: Record<string, string> = {
  plus: '<path fill="none" stroke="currentColor" stroke-width="0.95" stroke-linecap="round" d="M7 3.2v7.6M3.2 7h7.6"/>',
  "more-horizontal":
    '<circle cx="3.06" cy="7" r="0.8" fill="currentColor"/><circle cx="7" cy="7" r="0.8" fill="currentColor"/><circle cx="10.94" cy="7" r="0.8" fill="currentColor"/>',
  // Two strokes crossing. What a remove button is, where the button has no
  // room for the word — a bin is a picture of a container, and the thing
  // being removed is usually a line in a table, which does not go in a bin.
  close:
    '<path fill="none" stroke="currentColor" stroke-width="0.95" stroke-linecap="round" d="M3.8 3.8l6.4 6.4M10.2 3.8l-6.4 6.4"/>',
  // Two strokes meeting, the short one first. A state, not an object.
  tick: '<path fill="none" stroke="currentColor" stroke-width="1.05" stroke-linecap="round" stroke-linejoin="round" d="M2.9 7.3l2.6 2.6L11.1 4.1"/>',
  // The panel itself: a frame with a rail down one side. The control draws
  // what it opens, which is the one case where a picture is the right answer
  // and is still only rectangles.
  panel:
    '<path fill="none" stroke="currentColor" stroke-width="0.9" d="M2.5 3.1h9v7.9h-9zM5.5 3.1v7.9"/>',
};

/** What the application draws: the set, with our own marks over the top. */
export const GLYPHS: Record<string, string> = { ...FLEX, ...HOUSE };

/**
 * Names a module may ask for that mean the same thing as a drawn one.
 *
 * A module in another repository was built against whatever name it was
 * built against, and a picture is not worth breaking somebody's nav over.
 * Kept small and deliberate rather than growing into a synonym dictionary:
 * each line is a name that shipped before this set existed.
 */
const ALIASES: Record<string, string> = {
  shop: "shopping-cart",
  contacts: "contact-round",
  "calendar-days": "calendar",
  "id-card": "id-badge",
  icon: "layout",
  "check-circle": "check-square",
};

export type IconName = keyof typeof GLYPHS;

/**
 * What an unknown name draws: a plain box, deliberately nothing anybody drew,
 * so it is noticed and fixed rather than mistaken for a decision.
 */
const FALLBACK = '<path fill="currentColor" d="M2 2h10v10H2zm1 1v8h8V3z"/>';

/**
 * An unknown name draws the fallback rather than throwing.
 *
 * A module built against a later host will ask for icons this one has never
 * heard of, and a missing picture must never be why a sidebar fails to
 * render.
 */
export function Icon({
  name,
  size = 18,
}: {
  name: IconName | (string & {});
  size?: number;
}) {
  const body =
    GLYPHS[name] ?? GLYPHS[ALIASES[name] ?? ""] ?? GLYPHS.layout ?? FALLBACK;
  return (
    <svg
      width={size}
      height={size}
      // The grid the artwork is actually on, taken from the set rather than
      // assumed. See the note at the top of this file: it was assumed to be
      // 24 for weeks, and every icon was three-fifths the size it was drawn
      // at, in the corner of its own box.
      viewBox={`0 0 ${FLEX_GRID} ${FLEX_GRID}`}
      aria-hidden="true"
      focusable="false"
      className="shrink-0"
      /*
       * The markup is build-time constant: `icon-flex.ts` is generated
       * from a fixed map by a script in this repository, and the test beside
       * this file refuses a body carrying a script or an outside reference.
       * Nothing a user types reaches here.
       */
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated, constant icon markup
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
