/**
 * The platform's own icons.
 *
 * The drawings are the streamline-flex set, credited in `NOTICE` at the
 * root of this repository. They arrive as filled 24x24 paths, which is why
 * nothing here strokes anything: the weight is in the artwork.
 *
 * `icon-flex.ts` is generated by `scripts/fetch-icons.mjs`, and the map
 * of which drawing means what lives in that script — that is the file to
 * edit when a module needs an icon this set has never been asked for.
 *
 * Set by James on 21 September 2026, against a folder of samples: the icons
 * should look drawn rather than drafted.
 */
import { FLEX } from "./icon-flex";

/**
 * The marks that are geometry rather than pictures, drawn here.
 *
 * An icon set is drawn for icons, and a chevron, a plus and an ellipsis taken
 * from one arrive as small illustrations of those things — in the set's hand,
 * at the set's weight, beside a label they are meant to be subordinate to.
 * They are not illustrations. A plus is two strokes crossing. An ellipsis is
 * three dots. A caret is two hairlines meeting at a corner, and that one is
 * drawn in CSS because it also has to rotate.
 *
 * This set has no plus and no ellipsis at all, so the alternative was the
 * nearest picture that contained one — an application window with a plus in
 * the corner for "add a record", a telephone keypad for an overflow menu.
 * Both were placeholders and both said so in the map they came from.
 *
 * Stroked, not filled, unlike everything in FLEX: the weight of a rule is the
 * point of them. 1.6 at 24x24 renders as a hair over 1px at the 18px the app
 * draws, which is the weight of the rules beside them.
 *
 * Ours, so they carry no attribution and the NOTICE stays true to what it
 * describes.
 */
const HOUSE: Record<string, string> = {
  plus: '<path fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" d="M12 5.5v13M5.5 12h13"/>',
  "more-horizontal":
    '<circle cx="5.25" cy="12" r="1.35" fill="currentColor"/><circle cx="12" cy="12" r="1.35" fill="currentColor"/><circle cx="18.75" cy="12" r="1.35" fill="currentColor"/>',
  // Two strokes crossing. What a remove button is, where the button has no
  // room for the word — a bin is a picture of a container, and the thing
  // being removed is usually a line in a table, which does not go in a bin.
  close:
    '<path fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" d="M6.5 6.5l11 11M17.5 6.5l-11 11"/>',
  // Two strokes meeting, the short one first. A state, not an object.
  tick: '<path fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" d="M5 12.5l4.5 4.5L19 7"/>',
  // The panel itself: a frame with a rail down one side. The control draws
  // what it opens, which is the one case where a picture is the right answer
  // and is still only rectangles.
  panel:
    '<path fill="none" stroke="currentColor" stroke-width="1.5" d="M4.25 5.25h15.5v13.5H4.25zM9.5 5.25v13.5"/>',
};

/** What the application draws: the set, with our own marks over the top. */
export const GLYPHS: Record<string, string> = { ...FLEX, ...HOUSE };

/**
 * Names a module may ask for that mean the same thing as a drawn one.
 *
 * A module in another repository was built against whatever name it was
 * built against, and a picture is not worth breaking somebody's nav over.
 * Kept small and deliberate rather than growing into a synonym dictionary:
 * each line is a name that shipped before this set existed.
 */
const ALIASES: Record<string, string> = {
  shop: "shopping-cart",
  contacts: "contact-round",
  "calendar-days": "calendar",
  "id-card": "id-badge",
  icon: "layout",
  "check-circle": "check-square",
};

export type IconName = keyof typeof GLYPHS;

/**
 * What an unknown name draws: a plain box, deliberately nothing anybody drew,
 * so it is noticed and fixed rather than mistaken for a decision.
 */
const FALLBACK =
  '<path fill="currentColor" d="M4 4h16v16H4zm1.5 1.5v13h13v-13z"/>';

/**
 * An unknown name draws the fallback rather than throwing.
 *
 * A module built against a later host will ask for icons this one has never
 * heard of, and a missing picture must never be why a sidebar fails to
 * render.
 */
export function Icon({
  name,
  size = 18,
}: {
  name: IconName | (string & {});
  size?: number;
}) {
  const body =
    GLYPHS[name] ?? GLYPHS[ALIASES[name] ?? ""] ?? GLYPHS.layout ?? FALLBACK;
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      aria-hidden="true"
      focusable="false"
      className="shrink-0"
      /*
       * The markup is build-time constant: `icon-flex.ts` is generated
       * from a fixed map by a script in this repository, and the test beside
       * this file refuses a body carrying a script or an outside reference.
       * Nothing a user types reaches here.
       */
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated, constant icon markup
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
