/**
 * The platform's own icons.
 *
 * The drawings are the streamline-freehand set, credited in `NOTICE` at the
 * root of this repository. They arrive as filled 24x24 paths, which is why
 * nothing here strokes anything: the weight is in the artwork.
 *
 * `icon-freehand.ts` is generated by `scripts/fetch-icons.mjs`, and the map
 * of which drawing means what lives in that script — that is the file to
 * edit when a module needs an icon this set has never been asked for.
 *
 * Set by James on 21 September 2026, against a folder of samples: the icons
 * should look drawn rather than drafted.
 */
import { FREEHAND } from "./icon-freehand";

/** What the application draws. */
export const GLYPHS = FREEHAND;

/**
 * Names a module may ask for that mean the same thing as a drawn one.
 *
 * A module in another repository was built against whatever name it was
 * built against, and a picture is not worth breaking somebody's nav over.
 * Kept small and deliberate rather than growing into a synonym dictionary:
 * each line is a name that shipped before this set existed.
 */
const ALIASES: Record<string, string> = {
  shop: "shopping-cart",
  contacts: "contact-round",
  "calendar-days": "calendar",
  "id-card": "id-badge",
  icon: "layout",
  "check-circle": "check-square",
};

export type IconName = keyof typeof GLYPHS;

/**
 * What an unknown name draws: a plain box, deliberately nothing anybody drew,
 * so it is noticed and fixed rather than mistaken for a decision.
 */
const FALLBACK =
  '<path fill="currentColor" d="M4 4h16v16H4zm1.5 1.5v13h13v-13z"/>';

/**
 * An unknown name draws the fallback rather than throwing.
 *
 * A module built against a later host will ask for icons this one has never
 * heard of, and a missing picture must never be why a sidebar fails to
 * render.
 */
export function Icon({
  name,
  size = 18,
}: {
  name: IconName | (string & {});
  size?: number;
}) {
  const body =
    GLYPHS[name] ?? GLYPHS[ALIASES[name] ?? ""] ?? GLYPHS.layout ?? FALLBACK;
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      aria-hidden="true"
      focusable="false"
      className="shrink-0"
      /*
       * The markup is build-time constant: `icon-freehand.ts` is generated
       * from a fixed map by a script in this repository, and the test beside
       * this file refuses a body carrying a script or an outside reference.
       * Nothing a user types reaches here.
       */
      // biome-ignore lint/security/noDangerouslySetInnerHtml: generated, constant icon markup
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
